---
# vars file for project-roles/nagios-client
check_commands:
- "command[check_disk]=/usr/lib64/nagios/plugins/check_disk -w 20% -c 10% -p /"
- "command[check_swap]=/usr/lib64/nagios/plugins/check_swap -w 20% -c 10%"
- "command[check_dns]=/usr/lib64/nagios/plugins/check_dns -H devx-ntp001.ziyotek.local -s 192.168.1.165 -q ANY"